---
- import_tasks: "roles/ec2/tasks/ec2_creation.yml"
  tags:
    - ec2_creation

- import_tasks: "roles/ec2/tasks/dumb_docker.yml"
  tags:
    - dumb_docker

- import_tasks: "roles/ec2/tasks/dumb_deploy.yml"
  tags:
    - dumb_deploy

- import_tasks: "roles/ec2/tasks/dumb_deploy.yml"
  tags:
    - dumb_deploy2